version: "3"
services:
  database:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
      MONGO_INITDB_DATABASE: "wikiplag"
      MONGO_PASSWORD_FILE: /run/secrets/db-password
      MONGO_USER: "wikiplag"
    secrets:
      - db-root-password
      - db-password
    volumes:
      - db_data:/data/db
      - ./wiki-db/init:/docker-entrypoint-initdb.d/

  documents:
    build:
      context: ./wiki-documents
      dockerfile: Dockerfile.api
    restart: on-failure
    ports:
      - 8080:80
    secrets:
      - db-password
    depends_on:
      - database

secrets:
  db-root-password:
    file: ./wiki-db/db-root-password.txt
  db-password:
    file: ./wiki-db/db-password.txt

volumes:
  db_data: null
