FROM python:3.8

WORKDIR /usr/src

COPY requirements.txt .

RUN pip install --upgrade --no-cache-dir -r requirements.txt && python -m spacy download de_core_news_sm

COPY . /usr/src/app

WORKDIR /usr/src/app

CMD ["uvicorn", "wiki_nlp.api.app:app", "--host", "0.0.0.0", "--port", "80", "--timeout-keep-alive", "30"]